project_id = "atjpjmhumzfpotrkefaz"

[functions.create-donation]
verify_jwt = false

[functions.fetch-bible-chapter]
verify_jwt = false

[functions.import-scripture]
verify_jwt = true

[functions.process-zip-upload]
verify_jwt = true

[functions.send-notifications]
verify_jwt = false

[functions.send-scheduled-reminders]
verify_jwt = false

[functions.send-sms-notification]
verify_jwt = false

[functions.generate-streak-image]
verify_jwt = false

[functions.generate-campaign-achievement-image]
verify_jwt = false

[functions.generate-silhouette-avatar]
verify_jwt = false

[functions.create-monthly-donation]
verify_jwt = false

[functions.check-monthly-donation]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.send-donation-thank-you]
verify_jwt = false

[functions.send-cancellation-email]
verify_jwt = false

[functions.send-group-invitation-notification]
verify_jwt = false

[functions.send-leaderboard-notification]
verify_jwt = false

[functions.send-reaction-notification]
verify_jwt = false

[functions.send-friend-request-notification]
verify_jwt = false
