// GENERATED by scripts/gen-slide-images.mjs from scripts/slide-manifest.json.
// Public-domain artwork from Wikimedia Commons, matched to quest reading
// paragraphs. Edit the manifest and regenerate rather than editing this file.
import type { SlideImage } from "@/components/history/PaginatedReading";

import img1_eo_2_0 from "@/assets/history/slides/eo2-constantine.jpg";
import img2_eo_2_1 from "@/assets/history/slides/eo2-nicaea.jpg";
import img3_eo_2_2 from "@/assets/history/slides/eo2-athanasius.jpg";
import img4_eo_2_3 from "@/assets/history/slides/eo2-constantinople-381.jpg";
import img5_eo_2_4 from "@/assets/history/slides/eo2-ephesus.jpg";
import img6_eo_2_5 from "@/assets/history/slides/eo2-triumph-orthodoxy.jpg";
import img7_eo_3_0 from "@/assets/history/slides/eo3-anthony.jpg";
import img8_eo_3_1 from "@/assets/history/slides/eo3-basil.jpg";
import img9_eo_3_2 from "@/assets/history/slides/eo3-cyril-methodius.jpg";
import img10_eo_3_3 from "@/assets/history/slides/eo3-baptism-vladimir.jpg";
import img11_eo_3_4 from "@/assets/history/slides/eo3-deesis-mosaic.jpg";
import img12_eo_4_0 from "@/assets/history/slides/eo4-justinian.jpg";
import img13_eo_4_3 from "@/assets/history/slides/eo4-hagia-sophia.jpg";
import img14_eo_4_4 from "@/assets/history/slides/eo4-sack-1204.jpg";
import img15_eo_5_0 from "@/assets/history/slides/eo5-transfiguration.jpg";
import img16_eo_5_1 from "@/assets/history/slides/eo5-palamas.jpg";
import img17_eo_5_3 from "@/assets/history/slides/eo5-athos.jpg";
import img18_eo_5_5 from "@/assets/history/slides/eo5-fall-1453.jpg";
import img19_eo_5_6 from "@/assets/history/slides/eo5-gennadios.jpg";
import img20_eo_6_0 from "@/assets/history/slides/eo6-moscow-kremlin.jpg";
import img21_eo_6_1 from "@/assets/history/slides/eo6-rublev-trinity.jpg";
import img22_eo_6_2 from "@/assets/history/slides/eo6-morozova.jpg";
import img23_eo_7_0 from "@/assets/history/slides/eo7-peter.jpg";
import img24_eo_7_1 from "@/assets/history/slides/eo7-paisius.jpg";
import img25_eo_7_2 from "@/assets/history/slides/eo7-seraphim.jpg";
import img26_eo_7_3 from "@/assets/history/slides/eo7-innocent.jpg";
import img27_eo_7_4 from "@/assets/history/slides/eo7-greek-independence.jpg";
import img28_eo_8_0 from "@/assets/history/slides/eo8-tikhon.jpg";
import img29_eo_8_1 from "@/assets/history/slides/eo8-demolition-1931.jpg";
import img30_eo_8_2 from "@/assets/history/slides/eo8-romanovs.jpg";
import img31_eo_8_3 from "@/assets/history/slides/eo8-elizabeth.jpg";
import img32_eo_8_5 from "@/assets/history/slides/eo8-smyrna.jpg";
import img33_eo_9_1 from "@/assets/history/slides/eo9-stavropoleos.jpg";
import img34_eo_9_2 from "@/assets/history/slides/eo9-athos-karyes.jpg";
import img35_eo_9_5 from "@/assets/history/slides/eo9-household-icon.jpg";
import img36_eo_10_0 from "@/assets/history/slides/eo10-lavra.jpg";
import img37_eo_10_1 from "@/assets/history/slides/eo10-christ-savior.jpg";
import img38_eo_10_5 from "@/assets/history/slides/eo10-alexandria.jpg";
import img39_eo_11_2 from "@/assets/history/slides/eo11-kyiv-lavra.jpg";
import img40_eo_11_4 from "@/assets/history/slides/eo11-john-maximovitch.jpg";
import img41_eo_11_5 from "@/assets/history/slides/eo11-pentecost-fresco.jpg";
import img42_oo_1_0 from "@/assets/history/slides/oo1-mark.jpg";
import img43_oo_1_1 from "@/assets/history/slides/oo1-eunuch.jpg";
import img44_oo_1_2 from "@/assets/history/slides/oo1-gregory.jpg";
import img45_oo_1_3 from "@/assets/history/slides/oo1-syriac.jpg";
import img46_oo_1_4 from "@/assets/history/slides/oo1-macarius.jpg";
import img47_oo_2_0 from "@/assets/history/slides/oo2-chalcedon.jpg";
import img48_oo_2_2 from "@/assets/history/slides/oo2-cyril.jpg";
import img49_oo_2_4 from "@/assets/history/slides/oo2-coptic-homily.jpg";
import img50_oo_3_1 from "@/assets/history/slides/oo3-coptic-gospel.jpg";
import img51_oo_3_3 from "@/assets/history/slides/oo3-ethiopian-gospel.jpg";
import img52_oo_3_4 from "@/assets/history/slides/oo3-lalibela.jpg";
import img53_oo_3_5 from "@/assets/history/slides/oo3-mashtots.jpg";
import img54_oo_4_0 from "@/assets/history/slides/oo4-genocide.jpg";
import img55_oo_4_2 from "@/assets/history/slides/oo4-assyrian.jpg";
import img56_oo_4_3 from "@/assets/history/slides/oo4-coptic-cairo.jpg";
import img57_oo_5_2 from "@/assets/history/slides/oo5-addis-trinity.jpg";
import img58_oo_5_3 from "@/assets/history/slides/oo5-etchmiadzin.jpg";
import img59_oo_5_4 from "@/assets/history/slides/oo5-parumala.jpg";
import img60_oo_6_1 from "@/assets/history/slides/oo6-ethiopian-priests.jpg";
import img61_oo_6_2 from "@/assets/history/slides/oo6-christ-menas.jpg";
import img62_oo_6_3 from "@/assets/history/slides/oo6-anthony-monastery.jpg";
import img63_oo_6_4 from "@/assets/history/slides/oo6-ethiopian-mary.jpg";
import img64_oo_7_0 from "@/assets/history/slides/oo7-anthony-paul.jpg";
import img65_oo_7_1 from "@/assets/history/slides/oo7-pachomius.jpg";
import img66_oo_7_2 from "@/assets/history/slides/oo7-syncletica.jpg";
import img67_oo_7_4 from "@/assets/history/slides/oo7-simeon-stylite.jpg";
import img68_oo_8_1 from "@/assets/history/slides/oo8-censer.jpg";
import img69_oo_8_2 from "@/assets/history/slides/oo8-ephrem.jpg";
import img70_oo_8_3 from "@/assets/history/slides/oo8-roslin.jpg";

export const SLIDE_IMAGES: Record<string, Record<number, SlideImage>> = {
  "eo_2": {
    0: { src: img1_eo_2_0, alt: "The Vision of Constantine the Great before battle, icon by Stylianos Stavrakis", credit: "Icon by Stylianos Stavrakis, 18th century, public domain" },
    1: { src: img2_eo_2_1, alt: "The First Council of Nicaea, icon by Michael Damaskinos", credit: "Icon by Michael Damaskinos, 1591, public domain" },
    2: { src: img3_eo_2_2, alt: "Icon of Saint Athanasius of Alexandria, defender of the Nicene faith", credit: "Icon from Sozopol, Bulgaria, late 17th century, public domain" },
    3: { src: img4_eo_2_3, alt: "The First Council of Constantinople (381), Byzantine manuscript miniature", credit: "Homilies of Gregory the Theologian, Constantinople, c. 880 AD, public domain" },
    4: { src: img5_eo_2_4, alt: "The Third Ecumenical Council at Ephesus, sketch by Vasily Surikov", credit: "Vasily Surikov, 1876, sketch for the Cathedral of Christ the Saviour, public domain" },
    5: { src: img6_eo_2_5, alt: "Icon of the Triumph of Orthodoxy, the restoration of the holy icons", credit: "Byzantine icon, late 14th century, public domain" },
  },
  "eo_3": {
    0: { src: img7_eo_3_0, alt: "Icon of Saint Anthony the Great, father of desert monasticism", credit: "Icon, 16th century, public domain" },
    1: { src: img8_eo_3_1, alt: "Icon of Saint Basil the Great with scenes from his life", credit: "Icon by Semyon Spiridonov Kholmogorets, 1674, public domain" },
    2: { src: img9_eo_3_2, alt: "Icon of Saints Cyril and Methodius, missionaries to the Slavs", credit: "Icon in Saint Athanasius Church, Galatin, 1888, public domain" },
    3: { src: img10_eo_3_3, alt: "The Baptism of Prince Vladimir, by Viktor Vasnetsov", credit: "Viktor Vasnetsov, 1890, sketch for St Vladimir's Cathedral in Kiev, public domain" },
    4: { src: img11_eo_3_4, alt: "Christ Pantocrator from the Deesis mosaic in Hagia Sophia", credit: "Deesis mosaic, Hagia Sophia, 13th century, public domain" },
  },
  "eo_4": {
    0: { src: img12_eo_4_0, alt: "Mosaic of Emperor Justinian I and his court, Basilica of San Vitale, Ravenna", credit: "Byzantine mosaic, 6th century, public domain" },
    3: { src: img13_eo_4_3, alt: "The great nave of Hagia Sophia, where the excommunication of 1054 was laid on the altar", credit: "Lithograph by Louis Haghe after Gaspare Fossati, 1852, public domain" },
    4: { src: img14_eo_4_4, alt: "The Entry of the Crusaders into Constantinople in 1204, by Eugène Delacroix", credit: "Eugène Delacroix, 1840, public domain" },
  },
  "eo_5": {
    0: { src: img15_eo_5_0, alt: "The Transfiguration of Christ, icon by Theophanes the Greek — the uncreated light of Tabor", credit: "Theophanes the Greek, c. 1403, Tretyakov Gallery, public domain" },
    1: { src: img16_eo_5_1, alt: "Icon of Saint Gregory Palamas, defender of hesychasm", credit: "North Greek icon, early 15th century, Pushkin Museum, public domain" },
    3: { src: img17_eo_5_3, alt: "The Monastery of Docheiariou on Mount Athos, photographed in 1913", credit: "Autochrome photograph, Mount Athos, 1913, CC0" },
    5: { src: img18_eo_5_5, alt: "The Siege of Constantinople in 1453, manuscript miniature by Jean Le Tavernier", credit: "Jean Le Tavernier, after 1455, public domain" },
    6: { src: img19_eo_5_6, alt: "Patriarch Gennadios II with Sultan Mehmed II — the Church endures under Ottoman rule", credit: "Painting, 18th century, CC0" },
  },
  "eo_6": {
    0: { src: img20_eo_6_0, alt: "View of the Moscow Kremlin and its cathedrals from the Moskva River, 1850", credit: "Watercolour, 1850, public domain" },
    1: { src: img21_eo_6_1, alt: "The Holy Trinity icon by Andrei Rublev", credit: "Andrei Rublev, c. 1425, Tretyakov Gallery, public domain" },
    2: { src: img22_eo_6_2, alt: "Boyarynya Morozova, an Old Believer taken into exile, by Vasily Surikov", credit: "Vasily Surikov, 1887, Tretyakov Gallery, public domain" },
  },
  "eo_7": {
    0: { src: img23_eo_7_0, alt: "Portrait of Tsar Peter the Great, who replaced the Patriarchate with the Holy Synod", credit: "Godfrey Kneller, 1698, public domain" },
    1: { src: img24_eo_7_1, alt: "Saint Paisius Velichkovsky, reviver of the hesychast tradition", credit: "Portrait, 18th–19th century, public domain" },
    2: { src: img25_eo_7_2, alt: "Icon of Saint Seraphim of Sarov", credit: "Workshop of the Seraphimo-Diveevsky Monastery, after 1903, public domain" },
    3: { src: img26_eo_7_3, alt: "Saint Innocent of Alaska, missionary and translator, photographed in 1868", credit: "Photograph, 1868, State Historical Museum, public domain" },
    4: { src: img27_eo_7_4, alt: "Bishop Germanos of Old Patras blesses the banner of the Greek Revolution", credit: "Theodoros Vryzakis, 1865, public domain" },
  },
  "eo_8": {
    0: { src: img28_eo_8_0, alt: "Saint Tikhon, Patriarch of Moscow, elected in 1917", credit: "Photograph, Library of Congress, public domain" },
    1: { src: img29_eo_8_1, alt: "The demolition of the Cathedral of Christ the Saviour, Moscow, 5 December 1931", credit: "Photograph, 1931, public domain" },
    2: { src: img30_eo_8_2, alt: "Tsar Nicholas II and his family, the Royal Martyrs, in 1913", credit: "Photograph, 1913, public domain" },
    3: { src: img31_eo_8_3, alt: "Grand Duchess Elizabeth Feodorovna, the New Martyr Saint Elizabeth", credit: "Photograph, early 20th century, public domain" },
    5: { src: img32_eo_8_5, alt: "The Great Fire of Smyrna, 1922, seen from the sea", credit: "Photograph, 14 September 1922, public domain" },
  },
  "eo_9": {
    1: { src: img33_eo_9_1, alt: "Stavropoleos Church in Bucharest, a jewel of the Romanian Orthodox Church", credit: "Photograph, CC0" },
    2: { src: img34_eo_9_2, alt: "Sunrise at Karyes on Mount Athos, home of the holy elders", credit: "Autochrome photograph by Fernand Cuville, 1918, CC0" },
    5: { src: img35_eo_9_5, alt: "A Russian household icon of the Crucifixion with saints and feasts — the faith kept alive at home", credit: "Russian icon, 19th century, Walters Art Museum, public domain" },
  },
  "eo_10": {
    0: { src: img36_eo_10_0, alt: "The restored Trinity Lavra of Saint Sergius at Sergiev Posad", credit: "Photograph, 2016, CC0" },
    1: { src: img37_eo_10_1, alt: "The rebuilt Cathedral of Christ the Saviour in Moscow", credit: "Photograph, 2023, CC0" },
    5: { src: img38_eo_10_5, alt: "The Greek Orthodox Cathedral of the Annunciation in Alexandria, seat of the Patriarchate whose mission serves Africa", credit: "Photograph, public domain" },
  },
  "eo_11": {
    2: { src: img39_eo_11_2, alt: "The Dormition Cathedral of the Kyiv Pechersk Lavra", credit: "Photograph, 2013, CC0" },
    4: { src: img40_eo_11_4, alt: "The future Saint John Maximovitch of Shanghai and San Francisco as a young man", credit: "Photograph, Kharkov, early 20th century, public domain" },
    5: { src: img41_eo_11_5, alt: "Pentecost wall painting in the Church of Panagia Amasgou, Cyprus — the same Spirit fills the Church", credit: "Medieval wall painting, Monagri, Cyprus; Dumbarton Oaks field photograph, CC0" },
  },
  "oo_1": {
    0: { src: img42_oo_1_0, alt: "Saint Mark the Evangelist, founder of the Church of Alexandria, from a 10th-century Gospel manuscript", credit: "Gospel manuscript (Minuscule 1582), 948 AD, public domain" },
    1: { src: img43_oo_1_1, alt: "The Baptism of the Ethiopian Eunuch by Philip, painting by Rembrandt", credit: "Rembrandt, 1626, Museum Catharijneconvent, public domain" },
    2: { src: img44_oo_1_2, alt: "Saint Gregory the Illuminator with King Tiridates III of Armenia, manuscript illumination", credit: "Armenian manuscript, 1569, public domain" },
    3: { src: img45_oo_1_3, alt: "Christ holding the Gospel, miniature from a 6th-century Syriac manuscript", credit: "Syriac manuscript miniature, 6th century, public domain" },
    4: { src: img46_oo_1_4, alt: "Saint Macarius of Egypt and desert fathers, from a Russian icon", credit: "Lithograph of a Russian icon, 1846–1853, public domain" },
  },
  "oo_2": {
    0: { src: img47_oo_2_0, alt: "The Fourth Ecumenical Council of Chalcedon, by Vasily Surikov", credit: "Vasily Surikov, 1876, public domain" },
    2: { src: img48_oo_2_2, alt: "Saint Cyril of Alexandria (left) with Saint Athanasius, Novgorod icon", credit: "Novgorod school icon, late 15th century, public domain" },
    4: { src: img49_oo_2_4, alt: "Leaf from a Coptic Christian homily, Egypt, 6th–7th century", credit: "Coptic manuscript leaf, 6th–7th century, Cleveland Museum of Art, CC0" },
  },
  "oo_3": {
    1: { src: img50_oo_3_1, alt: "The Baptism of Christ, illumination from a Coptic-Arabic Gospel book", credit: "Coptic-Arabic Gospel illumination, c. 1250, public domain" },
    3: { src: img51_oo_3_3, alt: "Illuminated Ethiopian Gospel manuscript, Amhara, late 14th–early 15th century", credit: "Ethiopian illuminated Gospel, c. 1400, public domain" },
    4: { src: img52_oo_3_4, alt: "The rock-hewn church of Saint George (Bete Giyorgis) at Lalibela, drawn in 1882", credit: "Drawing by Achille Raffray, 1882, public domain" },
    5: { src: img53_oo_3_5, alt: "Saint Mesrop Mashtots, creator of the Armenian alphabet", credit: "Painting by Stepanos Nersissian, 1882, public domain" },
  },
  "oo_4": {
    0: { src: img54_oo_4_0, alt: "Armenian families deported from Kozan during the Armenian Genocide, 1915", credit: "Photograph, 1915, public domain" },
    2: { src: img55_oo_4_2, alt: "An Assyrian priest with an ancient manuscript among refugees at Tell-Tamar, 1939", credit: "Photograph, 1939, public domain" },
    3: { src: img56_oo_4_3, alt: "Coptic and Arabic inscriptions of the Gospel of John in a church of Old Cairo", credit: "Photograph, public domain" },
  },
  "oo_5": {
    2: { src: img57_oo_5_2, alt: "Holy Trinity Cathedral in Addis Ababa, Ethiopia", credit: "Photograph, 1969, CC0" },
    3: { src: img58_oo_5_3, alt: "Etchmiadzin Cathedral, mother church of the Armenian Apostolic Church", credit: "Photograph, 2024, CC0" },
    4: { src: img59_oo_5_4, alt: "Saint Gregorios of Parumala of the Malankara Orthodox Church, painted by Raja Ravi Varma", credit: "Raja Ravi Varma, 1905, public domain" },
  },
  "oo_6": {
    1: { src: img60_oo_6_1, alt: "Ethiopian Orthodox priests at Lalibela", credit: "Photograph, CC0" },
    2: { src: img61_oo_6_2, alt: "Christ and Abbot Mena, Coptic icon from Bawit, 6th century", credit: "Coptic icon, 6th century, Louvre, public domain" },
    3: { src: img62_oo_6_3, alt: "The Coptic Monastery of Saint Anthony by the Red Sea, inhabited for over 1,600 years", credit: "Photograph, 2006, public domain" },
    4: { src: img63_oo_6_4, alt: "Mary and her Son, Ethiopian triptych icon", credit: "Ethiopian icon, late 17th–early 18th century, Walters Art Museum, public domain" },
  },
  "oo_7": {
    0: { src: img64_oo_7_0, alt: "Saints Anthony the Great and Paul of Thebes, Coptic icon", credit: "Coptic icon, 14th century, public domain" },
    1: { src: img65_oo_7_1, alt: "The angel appearing to Saint Pachomius with the monastic rule, fresco", credit: "Fresco, Zrze Monastery, 14th century, public domain" },
    2: { src: img66_oo_7_2, alt: "Saint Syncletica of Alexandria, desert mother, from the Menologion of Basil II", credit: "Menologion of Basil II, c. 985 AD, public domain" },
    4: { src: img67_oo_7_4, alt: "Saint Simeon the Stylite on his pillar, icon of 1465", credit: "Icon, 1465, public domain" },
  },
  "oo_8": {
    1: { src: img68_oo_8_1, alt: "Bronze censer from Coptic Egypt, 6th–7th century", credit: "Coptic bronze censer, 6th–7th century, Metropolitan Museum of Art, CC0" },
    2: { src: img69_oo_8_2, alt: "The Dormition of Saint Ephrem the Syrian, who taught the faith through hymns", credit: "Cretan icon, 15th century, Byzantine Museum, public domain" },
    3: { src: img70_oo_8_3, alt: "Canon table page by Toros Roslin, Armenian illuminated manuscript", credit: "Toros Roslin, 1256, Getty Museum, public domain" },
  },
};
